### ISSUE TITLE
Bug:  Initial DL events not caught in Rules

### ISSUE THREAD

**Issue by brobatr** [adobe/reactor-extension-googledatalayer#14]
@ogillies please check and add any detail.  I will be able to work on this from 14.08

### Expected Behaviour

Tags rules can catch all events in DL history on instantiation.

### Actual Behaviour

Some events are not caught.  Assumption is that the Tags listeners are not created quickly enough to catch the DL instantiation.

**Comment by ogillies** [comment]
Thanks @brobatr 

Steps to reproduce:

Using the extension I have a tag library with 2 rules, each listening for a specific event (sfmcCollectLoaded, ecommerceDetail) - the rule action just logs to the console.  The ecommerceDetail event is consistently skipped. 

![image](https://user-images.githubusercontent.com/78716088/184590493-f2e81240-930b-4144-a890-c53bddc6b776.png)

If I remove the extension and deploy the GTM Helper library using a custom code rule on window loaded and a direct call in the listener all events are consistently caught and both rules fire: 

![image](https://user-images.githubusercontent.com/78716088/184590206-ef758db5-2612-4b27-a558-358bb6bacd1d.png)

**Comment by brobatr** [comment]
solved my moving the helper instantiation after the listener is created
